version: '3'

services:
  generator:
    image: my-registry:55000/gen:ci-${GENERATOR_BUILD_NUMBER-10}
    ports:
      - "${PORT_GENERATOR-8080}:80"
  mail:
    image: mailhog/mailhog
    ports:
      - "${PORT_MAILHOG-8081}:8025"